### ISSUE TITLE
Milestone: Read-Only ZFGC.com

### ISSUE THREAD

**Issue by gm112** [ZFGCCP/ZFGCBB#28]
ZFGC.com currently is offline due to technical issues with SMF and its database. We've decided to just simply move the site to the new schema and deploy it to ZFGC.com using a read only approach for the database.

## Requirements

We must be able to...

### Navigation Requirements
- [ ] View the site index
- [ ] Browse the forum index
- [ ] Browse public forum categories
- [ ] Browse public forum threads

### Functionality Requirements
- [ ] Data must be retrieved from a Postgres DB
- [ ] The SMF DB should be able to be serialized into the new Postgres DB
- [ ] BBCode present in the DB should be properly interpreted
- [ ] Associated user data with posts should be imported with enough data to fulfill the requirements of rendering a post in a thread

**Comment by gm112** [comment]
I am closing this issue as of #143 ! 2026.05.03.1 release gets us basically almost the entire forum, aside from maybe an edge case here or there. This is huge!!!
